#makefile for reseplanerare
#
#
CC=gcc 
CFlags= -Wall -ggdb -std=c99



complete:list.h list.c graph.c graph.h
	$(CC) $(CFlags) list.h list.c graph.c graph.h -o main

all: list.o graph.o main.o
	$(CC) $(CFlags) main.o list.o graph.o -o main


main: main.c
	$(CC) $(CFlags) -c main.c

list:list.h list.c
	$(CC) $(CFlags) -c list.c list.h

graph:graph.c graph.h
	$(CC) $(CFlags) -c graph.c graph.h